### ISSUE TITLE
Outstanding!

### ISSUE THREAD

**Issue by cartercherry** [pageauc/rpi-speed-camera#1]
**Brilliant**, innovative program.  Thanks for sharing  your thoughtful ideas.  I've learned a great deal from your projects. 

It would be great to distinguish direction of motion, logging to csv file - analyze data by direction (uphill vs downhill in my case).  I'll work on that as soon as I understand your code more thoroughly.   I'm new to openCV.

Thanks!
Carter Cherry, appreciative follower of your work
Morgan Hill, CA

**Comment by pageauc** [comment]
Added Movement Direction in messages and CSV.  Also the new version has a menubox.sh whiptail menuing system plus a webserver for viewing speed images with associated data.  Also added detailed wiki instructions including start on boot.
Claude ...
